import Head from "next/head";
import Image from "next/image";
import { SiKia, SiHonda } from "react-icons/si";

import Navbar from "./Navbar/Navbar";
import styles from "./Layout.module.css";

const Layout = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <div className={styles.image_container}>
        <div className={styles.image_box_wrapper}>
          <div className={styles.image_box}>
            <div className={styles.image_box_left}>
              <h3>Smooth, Rich & Loud Audio</h3>
              <h4>Branded Cars</h4>
              <p>Sale up to 25% off all in store</p>
            </div>
            <div className={styles.image_box_right}>
              <SiHonda fontSize="150" />
            </div>
          </div>
          <div className={styles.image_box}>
            <div className={styles.image_box_left}>
              <h3>A Better Ride</h3>
              <h4>KIA</h4>
              <p>Free shipping order over $100</p>
            </div>
            <div className={styles.image_box_right}>
              <SiKia fontSize="150" />
            </div>
          </div>
        </div>
      </div>
      <div className={styles.footer_container}>
        <p>© 2018 Electro Store. All rights reserved | Design by W3layouts.</p>
      </div>
    </div>
  );
};

export default Layout;
